# Plugins
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji

# Conversion
# markdown: redcarpet
# highlighter: pygments
excerpt_separator: ""

# Outputting
permalink: "/:title"
paginate_path: "/pagina-:num"
paginate: 10
timezone: America/Sao_Paulo

# Markdown Processors
kramdown:
  input: GFM

# Site settings
title: "Thiago Belem / Blog"
description: Artigos e tutoriais sobre desenvolvimento WEB
logo: http://gravatar.com/avatar/67a6eb9b43b617b2051b912b8373a156?s=120
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
url: "http://blog.thiagobelem.net"

# Default author
author:
  name: Thiago Belem
  image: http://gravatar.com/avatar/67a6eb9b43b617b2051b912b8373a156?s=120

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/TiuTalk
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url:  https://github.com/TiuTalk
    desc: Fork me on github
    share_url:
    share_title:
    share_link:
